### PR TITLE
Delete and ignore Cargo.lock

### PR DESCRIPTION
**Pull request by GitGhillie**
Afaik libraries should not have their Cargo.lock in the repository (see bevy repo for example).
When I cloned and built this repo I got some weird regex parsing errors until I deleted Cargo.lock and rebuilt.

### CODE REVIEW

**Comment by Salzian** [comment]
Good catch! This is my first library and totally an oversight on my side. [According to the cargo book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html), libraries, like this repo, should ignore the Cargo.lock file. 

As the example project provides an example of a basic application, I think the Cargo.lock file should maybe stay in that case? So the gitignore should only reference the root lock file. What do you think?

**Comment by Salzian** [comment]
Oops, sorry with the assignees. Force of habit 😅

**Comment by GitGhillie** [comment]
> As the example project provides an example of a basic application, I think the Cargo.lock file should maybe stay in that case? So the gitignore should only reference the root lock file. What do you think?

True, but if you agree with https://github.com/Salzian/bevy_fmod/pull/9 then I don't think it's worth it to fix this anymore. Because that PR removes the need for Cargo.toml and Cargo.lock in examples altogether

**Comment by Salzian** [comment]
Then I'll have a look at #9 first.

**Comment by Salzian** [comment]
Can you take a look if there's something in here that's still relevant?

**Comment by GitGhillie** [comment]
All fixed with https://github.com/Salzian/bevy_fmod/pull/10

**Pull request closed without merging**
