### PR TITLE
Remove smooth-bevy-cameras dependency from spatial example

### PR DESCRIPTION
**Pull request by GitGhillie**
This will make it easier to update bevy_fmod for new releases of Bevy.
Took some inspiration from the Bevy spatial example.
Feedback welcome!

### CODE REVIEW

**Review by Salzian — DISMISSED** [review]
Nice simplification. Small improvement idea: Spawn the camera further back so the Doppler effect is immediately present.

**Comment by GitGhillie** [comment]
Assuming you mean the spatial effect; I've now adjusted it so the cube is in view the whole time. Let me know what you think, I think it's better

**Comment by Salzian** [comment]
I guess this becomes obsolete with #60 ? Then we can close this PR.

**Comment by GitGhillie** [comment]
IMO it's still a good move, we'll run into the same issue when preparing for 0.13, 0.14, etc.
Up to you

**Review by Salzian — APPROVED** [review]

**Pull request merged**
